<?php
  $category=stripslashes($_POST["category"]);
  $to_email=stripslashes($_POST["email"]);
  $from_email='shameer@neointeraction.com';
  $subject = 'Brouchure';
  $okMessage = 'Brouchure send to your mail please check your mail.';
  $errorMessage = 'There was an error while submitting the form. Please try again later';
  $serverpath = $_SERVER['HTTP_HOST']. '/beta/pdf';
  try
  {
      if (!empty($_POST)) {

         if($to_email){
            // To send HTML mail, the Content-type header must be set
            $headers  = 'MIME-Version: 1.0' . "\r\n";
            $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
            $headers .= "X-Mailer: Mail generated by:ultramtics.com\r\n";
            //       Additional headers
            $headers .= 'Reply-To:'.$from_email."\r\n" ;
            $headers .= 'From: '.$from_email. "\r\n";   
			$strMessageBody .='<h4 style="font-weight: 400;font-size: 18px; color: #000;">Click the below files to download the brochure </h4>';
            if($category=='fintech'){
               $strMessageBody .=' <a href="'.$serverpath.'/Arya (Internet & Mobile Banking).pdf" target="_blank" style="font-weight: 400;font-size: 14px; letter-spacing: 0; line-height: 20px; display:block;">Arya (Internet & Mobile Banking)</a>';
              $strMessageBody .='<a href="'.$serverpath.'/Jeb (Payment Solution).pdf" target="_blank" style="font-weight: 400;font-size: 14px;  letter-spacing: 0; line-height: 20px; display:block;">Jeb (Payment Solution)</a>';
            }else if($category=='offering_ds'){
				 $strMessageBody .=' <a href="'.$serverpath.'/eMudhra Solutions.pdf" target="_blank" style="font-weight: 400;font-size: 14px; letter-spacing: 0; line-height: 20px; display:block;">eMudhra Solutions</a>';
			}else if($category=='offering_rad'){
				 $strMessageBody .=' <a href="'.$serverpath.'/OutSystems.pdf" target="_blank" style="font-weight: 400;font-size: 14px; letter-spacing: 0; line-height: 20px; display:block;">OutSystems</a>';
			}
			
            $success = mail($to_email, $subject, $strMessageBody, $headers) ; 
            $responseArray = array('type' => 'success', 'message' => $okMessage);
        }
                
          
      }
  }
  catch (Exception $e)
  {
      $responseArray = array('type' => 'danger', 'message' => $errorMessage);
  }

  if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
      $encoded = json_encode($responseArray);
      echo $encoded;
  }
  else {
      echo $responseArray['message'];
  }

?>