<?php
if($_SERVER['REQUEST_METHOD']=="POST")
{   
    if($_POST['Name'])
    {   
        $msg='';
        $recaptcha=$_POST['g-recaptcha-response'];
        if(!empty($recaptcha))
        {
            
            include("getCurlData.php");
            $google_url="https://www.google.com/recaptcha/api/siteverify";
            $secret='6LfYRRcTAAAAACpAYm4--C0ddbzmEBowBwEEIhPu';
            $ip=$_SERVER['REMOTE_ADDR'];
            $url=$google_url."?secret=".$secret."&response=".$recaptcha."&remoteip=".$ip;
            $res=getCurlData($url);
            $res= json_decode($res, true);
            if($res['success'])
            {
                
                header("location: thankyou.php");
            }
            else
            {
             $msg="Please re-enter your reCAPTCHA.";
            }

        } 
        
    
            $category = "Contact Us"; 
            $sname = stripslashes($_POST['Name']);    
            $useremail = stripslashes($_POST['email']); 
            $phone = stripslashes($_POST['Phone']);   
            $message = stripslashes($_POST['message']);    
            $toEemail = "info@neointeraction.com";
            $subject = "Neo-Contact us: ";
        
        // To send HTML mail, the Content-type header must be set
                      $headers  = 'MIME-Version: 1.0' . "\r\n";
                      $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
                      $headers .= "X-Mailer: Mail generated by:ultramtics.com\r\n";
                //       Additional headers
                      $headers .= 'Reply-To:'.$useremail."\r\n" ;
                      $headers .= 'From: '.$useremail. "\r\n";   
                      $strMessageBody ='Name                : '.$sname.'<br>';
                      $strMessageBody .='Email              : '.$useremail.'<br>';
                      $strMessageBody .='Phone              : '.$phone.'<br>';
                      $strMessageBody .='Message category : '.$category.'<br>';
                      $strMessageBody .='Message Description : '.$message.'<br>';
                      
                    mail($toEemail, $subject, $strMessageBody, $headers) ;  
        
                            
                    
                     
        
    }
   

 }
?>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <title>UI/UX Design Services for Enterprise & Startups, Web & Mobile Applications</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="User experience design company, based in Bangalore, specialising in product and service design for business applications. We increase customer engagement & conversion & drive your digital revenue streams." />    
    <meta name="keywords" content="Ux,uxd,ux design, user experience design,GUI Design">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="assets/images/neo_fav.ico">
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Global CSS -->
    <link rel="stylesheet" href="assets/css/wrapped_styles.css" type='text/css'>
      <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12661901-1', 'auto');
  ga('send', 'pageview');

</script>

</head>

<body>
    <div class="wrapper">
        <!-- ******HEADER****** -->
        <?php include( "header.php"); ?>
        <!--//header-->

        <!-- ******ProjectDetail****** -->
        <div id="uxdetails" class="why  section Ux-service">
            <div class="blog container containeruxupdate">
                <div class="row">
                    <div id="blog-entry" class="blog-entry section col-md-9 col-sm-9 col-xs-12">
                        <article class="post">
                            <h2 class="title">Contact Us</h2>
                            <form name="contact-us" method="post" id="contact-val-Form">
                                <div class="form-group">
                              
                                    <div class="item clearfix">
                                        <div class="content col-md-12 col-xs-12">
                                            <input type="text" id="Name" name="Name" class="form-control " placeholder="Name">
                                        </div>
                                    </div>
                                    <!--//item-->
                                </div>
                                <!--//form-group-->
                                <div class="form-group">
                                    <div class="item clearfix">
                                        <div class="content col-md-12 col-xs-12 col-sm-12">
                                            <input type="email" id="email" name="email" class="form-control " placeholder="Email">
                                        </div>
                                    </div>
                                    <!--//item-->
                                </div>
                                <!--//form-group-->
                                <div class="form-group">
                                    <div class="item clearfix">
                                        <div class="content col-md-12 col-xs-12 col-sm-12">
                                            <input type="text" id="Phone" name="Phone" class="form-control " placeholder="Phone Number" maxlength="12">
                                        </div>
                                    </div>
                                    <!--//item-->
                                </div>
                                <!--//form-group-->
                                <div class="form-group">
                                    <div class="item clearfix">
                                        <div class="content col-md-12 col-xs-12 col-sm-12">
                                             <textarea id="message" placeholder="Your message" name="message" class="form-control " rows="3" cols="1"></textarea>
                                        </div>
                                    </div>
                                    <!--//item-->
                                </div>
                                <div class="form-group">
                                    <div class="item clearfix">
                                        <div class="content col-md-12 col-xs-12 col-sm-12">
                                            <script src='https://www.google.com/recaptcha/api.js'></script>
                                            <div class="g-recaptcha" data-sitekey="6LfYRRcTAAAAAIrvugm6q5jr3dNfPEefmV02Xeeh" id="html_element"></div>
                                                <br/>
                                                <p class="error-captcha " style="color:red;" id="captcha-error"><span class="glyphicon glyphicon-remove " ></span> Please fill up the captcha.</p>
                                        </div>
                                    </div>
                                    <!--//item-->
                                </div>
                                
                               
                                <input type="hidden" name="hiddenvalue" id="hiddenval" value=""/>
                                <!--//form-group-->
                                <div class="form-group mgip10">
                                    <div class="item clearfix">
                                        <div class="content col-md-12 col-xs-12">
                                            <button class="btnsubmit hvr-bounce-to-right" type="submit">SUBMIT</button>
                                        </div>
                                    </div>
                                    <!--//item-->
                                   </div>
                            </form>
                        </article>

                    </div>
                    <!--//blog-entry-->

                    <aside id="blog-sidebar" class="blog-sidebar col-md-3 col-sm-3 col-xs-12 col-sm-offset-0 col-xs-offset-0 Ux-service">

                        <div id="swapper-first" style="display:block;">
                            <div class="Off_address">
              <div class="Off_address_cont">
                    <p>Office Address</p>
                    <p>Neointeraction Designs</p>
                    <p>#50, 1st Cross, HAL 3rd Stage,</p>
                    <p>Bangalore - 560 075</p>
                    <p class="tel "><i class="fa fa-phone"></i>+91-944 9565 744<br/>
                         &nbsp; &nbsp; &nbsp;  +91-80-40953785 </p>
                    <p class="email"><i class="fa fa-map-marker"></i><a href="javascript:SwapDivsWithClick('swapper-first','swapper-other')">Office Location</a></p>
                    <p>info@neointeraction.com</p>
                </div>
              </div>


                        </div>
                        <div id="swapper-other" style="display:none;">
                        <p style="text-align: left;font-weight:bold; font-style:italic;"><a href="javascript:SwapDivsWithClick('swapper-first','swapper-other')">back</a></p>
                       <p class="Off_address">Check Office Location</p>
                  <!-- <div id="map-canvas" class=""></div> -->
                    <div style="width: 100%;">
                       <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7775.854635349726!2d77.64616467372413!3d12.976500513410565!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae16ae4b33f91d%3A0x16ae479052c160f0!2sNeointeraction+%7C+UI%2FUx+Design+Services+for+Web+%26+Mobile+Platforms!5e0!3m2!1sen!2sin!4v1491897097706" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                  <div class="Off_address">
                      <div class="Off_address_cont">
                            <p>Office Address</p>
                            <p>Neointeraction Designs</p>
                            <p>#50, 1st Cross, HAL 3rd Stage,</p>
                            <p>Bangalore - 560 075</p>
                            <p class="tel "><i class="fa fa-phone"></i> +91-944 9565 744<br/>
                            &nbsp; &nbsp;  &nbsp; &nbsp;+91-80-40953785 </p>
                            <p>info@neointeraction.com</p>
                        </div>
                      </div>  
                        </div>


                    </aside>
                    </div>
                     </div>
                    <!--//blog-side-bar-->

        </div>
        </div>
        <!--//wrapper-->
        <!-- ******FOOTER****** -->
        <?php include( "footer.php")?>
        <!--//footer-->

        <!-- *****CONFIGURE STYLE****** -->

        <?php include( "project-list.php")?>

        <!-- Javascript -->
        <script type="text/javascript" src="assets/plugins/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="assets/plugins/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="assets/plugins/jquery-ui.js"></script>
        <script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="assets/plugins/bootstrap-hover-dropdown.min.js"></script>
        <script type="text/javascript" src="assets/plugins/jquery-inview/jquery.inview.min.js"></script>
        <script type="text/javascript" src="assets/plugins/isMobile/isMobile.min.js"></script>
        <script type="text/javascript" src="assets/plugins/back-to-top.js"></script>
        <script type="text/javascript" src="assets/plugins/jquery-placeholder/jquery.placeholder.js"></script>
        <script type="text/javascript" src="assets/plugins/FitVids/jquery.fitvids.js"></script>
        <script type="text/javascript" src="assets/plugins/flexslider/jquery.flexslider-min.js"></script>
        <script type="text/javascript" src="assets/plugins/formvalidation/formValidation.min.js"></script>
        <script type="text/javascript" src="assets/plugins/formvalidation/bootstrapValidator.js"></script>

        <!--Scroll -->
        <script type="text/javascript" src="assets/plugins/custom-scroll/jquery.mCustomScrollbar.concat.min.js"></script>


        <script type="text/javascript" src="assets/js/main.js"></script>
        <!--[if !IE]>-->
        <script type="text/javascript" src="assets/js/animations.js"></script>
        <!--<![endif]-->
        <!-- Google map-->
        <script src="https://maps.googleapis.com/maps/api/js"></script>
        <script type="text/javascript">
            function SwapDivsWithClick(div1,div2)
            {
               d1 = document.getElementById(div1);
               d2 = document.getElementById(div2);
               if( d2.style.display == "none" )
               {
                  d1.style.display = "none";
                  d2.style.display = "block";
               }
               else
               {
                  d1.style.display = "block";
                  d2.style.display = "none";
               }
            }
        </script>
        



</body>

</html>